export const environment = {
  production: true,
  homePath: '/main/home',
  authApiUrl: 'https://val-api.vmsl.live/auth-service',
  userApiUrl: 'https://val-api.vmsl.live/tenant-user-facade',
  chatApiUrl: 'https://val-api.vmsl.live/chat-facade',
  clientId: 'webapp',
  clientSecret: 'saqw21!@',
  messageTimeout: 5000,
  mock: false,
  baseUrl: 'https://val.vmsl.live',
  recaptchaKey: '6LcWPLMZAAAAAHVQp5hKiC4BB62Eqc2TqDiS9V4K',
  orgId: '',
  debug: false,
  namespace: 'FS',
  defaultClientId: '555c81ff-2808-42f9-92c8-9d1598e77bf2',
  defaultTenantId: '831117d8-8fb9-11ea-9ce0-0e965b29d6db',
};
